#!/usr/bin/env bash
# Full indexer replay. Uses the same workspace, database and cleanup as tests.
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
source "$REPO_ROOT/scripts/podman/test-stack.sh"

if [[ "${1:-}" == --help || "${1:-}" == -h ]]; then
  printf '%s\n' \
    "Usage: bash scripts/podman/block-test.sh <project-spec.yaml> <start-block> [subql-node args...]" \
    "Default: built workspace. USE_IMAGE_PROJECT=1: bundled project; USE_IMAGE_SPEC=1: bundled manifest." \
    "Overrides: SUBQL_NODE_IMAGE, IMAGE_PROJECT_ROOT, WORKSPACE_VOLUME, ENV_FILE, RPC_ENDPOINT_OVERRIDE," \
    "           PG_IMAGE, DB_PORT (optional, localhost only), DB_USER, DB_PASS, DB_NAME, DB_SCHEMA." \
    "See doc/runbooks/block-failure.md"
  exit
fi
[[ $# -ge 2 ]] || die "Expected a project spec and start-block; see --help"
spec="$1"
block="$2"
shift 2
[[ "$spec" =~ ^project-[a-z0-9-]+\.yaml$ ]] || die "Expected project-<chain>.yaml"
[[ "$block" =~ ^[0-9]+$ ]] || die "start-block must be an integer"
for flag in USE_IMAGE_PROJECT USE_IMAGE_SPEC; do
  [[ "${!flag:-0}" =~ ^[01]$ ]] || die "$flag must be 0 or 1"
done
[[ "${USE_IMAGE_SPEC:-0}" != 1 || "${USE_IMAGE_PROJECT:-0}" == 1 ]] ||
  die "USE_IMAGE_SPEC=1 requires USE_IMAGE_PROJECT=1"
require_podman
env_file_args

project_dir=/work
MOUNT_ARGS=()
if [[ "${USE_IMAGE_PROJECT:-0}" == 1 ]]; then
  project_dir="${IMAGE_PROJECT_ROOT:-/project}"
else
  require_workspace
  MOUNT_ARGS=(-v "$WORKSPACE_VOLUME:/work")
fi
if [[ "${USE_IMAGE_SPEC:-0}" == 1 ]]; then
  source_spec="$project_dir/$spec"
else
  [[ -f "$REPO_ROOT/$spec" ]] || die "Project manifest not found: $spec"
  source_spec="/src/$spec"
fi

umask 077
tmp_dir="$(mktemp -d)"
init_stack
cleanup() {
  cleanup_stack
  rm -rf "$tmp_dir"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
trap 'exit 129' HUP

# YAML is generated by a structured parser in the runtime container, never awk.
# A secret RPC override stays in env and a mode-0600 temporary file.
podman run --rm --entrypoint node -v "$REPO_ROOT:/src:ro,Z" \
  "${MOUNT_ARGS[@]}" -e RPC_ENDPOINT_OVERRIDE "${ENV_ARGS[@]}" "$SUBQL_NODE_IMAGE" \
  /src/scripts/lib/block-spec.js "$source_spec" "$block" >"$tmp_dir/replay.yaml"
if [[ -n "${PG_IMAGE:-}" ]]; then
  PG_TEST_IMAGE="$PG_IMAGE"
else
  build_pg_image
fi
start_stack
printf 'Replaying %s from block %s with %s\n' "$spec" "$block" "$SUBQL_NODE_IMAGE"
NODE_ARGS=("$@")
# Repeating numeric options can make yargs return an array instead of a number.
for default in "--db-schema=${DB_SCHEMA:-app}" --batch-size=30; do
  key="${default%%=*}"
  present=false
  for arg in "$@"; do
    if [[ "$arg" == "$key" || "$arg" == "$key="* ]]; then present=true; fi
  done
  if ! "$present"; then NODE_ARGS+=("$default"); fi
done
run_stack_node --rm --name "$SQ_NAME" --label "$RESOURCE_LABEL=true" --network "$NET_NAME" \
  "${DB_ARGS[@]}" "${MOUNT_ARGS[@]}" \
  -v "$tmp_dir/replay.yaml:$project_dir/.block-replay.yaml:ro,Z,U" -w "$project_dir" \
  "$SUBQL_NODE_IMAGE" "-f=$project_dir/.block-replay.yaml" "${NODE_ARGS[@]}"
