specVersion: 1.0.0
name: subquery-spektr
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: v1.5.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-proxy
schema:
  file: ./schema.graphql
network:
  chainId: "0x6408de7737c59c238890533af25896a2c20608d8b380bb01029acb392781063e"
  endpoint: >-
    wss://rococo-rpc.polkadot.io
  dictionary: https://api.subquery.network/sq/subquery/rococo-dictionary
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 3152590
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: PureCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: AnonymousCreated
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: asMulti
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: approveAsMulti
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: cancelAsMulti
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: asMultiThreshold1
            success: true
            isSigned: true
