specVersion: 1.0.0
name: subquery-proxy-westend-asset-hub
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: v1.5.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-proxy
schema:
  file: ./schema.graphql
network:
  chainId: "0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9"
  endpoint: >-
    wss://sys.ibp.network/asset-hub-westend
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 11990129 # first multisig remark with data
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handlePureProxyEvent
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: PureCreated
        - handler: handlePureProxyEvent
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: AnonymousCreated

        - handler: handleMultisigInProxy
          kind: substrate/CallHandler
          filter:
            module: proxy
            method: proxy
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: asMulti
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: approveAsMulti
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: cancelAsMulti
            success: true
            isSigned: true
        - handler: handleMultisigCall
          kind: substrate/CallHandler
          filter:
            module: multisig
            method: asMultiThreshold1
            success: true
            isSigned: true        
        - handler: handleMultisigRemarkEventHandler
          kind: substrate/EventHandler
          filter:
            module: system
            method: Remarked
        - handler: handleProxyEvent
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyAdded
        - handler: handleProxyEvent
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyRemoved    
