name: PR check
on:
  pull_request:

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enable corepack
        run: corepack enable
      - name: Install
        run: yarn install
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build

  test:
    name: subql-node test (Polkadot Asset Hub)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enable corepack
        run: corepack enable
      - name: Install
        run: yarn install
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Run subql-node test
        run: scripts/run-tests.sh polkadot-asset-hub
